==64886== Helgrind, a thread error detector
==64886== Copyright (C) 2007-2017, and GNU GPL'd, by OpenWorks LLP et al.
==64886== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==64886== Command: ./da_proc 2 membership 300000
==64886== Parent PID: 64882
==64886== 
==64886== ---Thread-Announcement------------------------------------------
==64886== 
==64886== Thread #11 was created
==64886==    at 0x4CED2C2: clone (in /usr/lib/libc-2.30.so)
==64886==    by 0x4BD438B: create_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4BD5CFB: pthread_create@@GLIBC_2.2.5 (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x483F677: pthread_create_WRK (hg_intercepts.c:427)
==64886==    by 0x49521A9: __gthread_create (gthr-default.h:663)
==64886==    by 0x49521A9: std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (thread.cc:135)
==64886==    by 0x115230: thread<main(int, char**)::<lambda()> > (thread:130)
==64886==    by 0x115230: make_unique<std::thread, main(int, char**)::<lambda()> > (unique_ptr.h:849)
==64886==    by 0x115230: main (da_proc.cc:156)
==64886== 
==64886== ---Thread-Announcement------------------------------------------
==64886== 
==64886== Thread #2 was created
==64886==    at 0x4CED2C2: clone (in /usr/lib/libc-2.30.so)
==64886==    by 0x4BD438B: create_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4BD5CFB: pthread_create@@GLIBC_2.2.5 (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x483F677: pthread_create_WRK (hg_intercepts.c:427)
==64886==    by 0x49521A9: __gthread_create (gthr-default.h:663)
==64886==    by 0x49521A9: std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (thread.cc:135)
==64886==    by 0x11A05F: thread<da::executor::Executor::Worker> (thread:130)
==64886==    by 0x11A05F: da::executor::Executor::Executor(int) (executor.cc:12)
==64886==    by 0x114CC2: make_unique<da::executor::Executor, long unsigned int> (unique_ptr.h:849)
==64886==    by 0x114CC2: main (da_proc.cc:131)
==64886== 
==64886== ----------------------------------------------------------------
==64886== 
==64886== Possible data race during read of size 8 at 0x4DDC880 by thread #11
==64886== Locks held: none
==64886==    at 0x11DDE6: _M_ptr (unique_ptr.h:154)
==64886==    by 0x11DDE6: get (unique_ptr.h:353)
==64886==    by 0x11DDE6: release (unique_ptr.h:375)
==64886==    by 0x11DDE6: unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter> (unique_ptr.h:264)
==64886==    by 0x11DDE6: ~packaged_task (future:1507)
==64886==    by 0x11DDE6: destroy<std::packaged_task<void()> > (new_allocator.h:153)
==64886==    by 0x11DDE6: destroy<std::packaged_task<void()> > (alloc_traits.h:497)
==64886==    by 0x11DDE6: std::_Sp_counted_ptr_inplace<std::packaged_task<void ()>, std::allocator<std::packaged_task<void ()> >, (__gnu_cxx::_Lock_policy)2>::_M_dispose() (shared_ptr_base.h:557)
==64886==    by 0x14007A: _M_release (shared_ptr_base.h:155)
==64886==    by 0x14007A: _M_release (shared_ptr_base.h:148)
==64886==    by 0x14007A: ~__shared_count (shared_ptr_base.h:730)
==64886==    by 0x14007A: ~__shared_ptr (shared_ptr_base.h:1169)
==64886==    by 0x14007A: ~shared_ptr (shared_ptr.h:103)
==64886==    by 0x14007A: add<da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::<lambda()> > (executor.h:76)
==64886==    by 0x14007A: da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*) (receiver.cc:28)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4CED2D2: clone (in /usr/lib/libc-2.30.so)
==64886== 
==64886== This conflicts with a previous write of size 8 by thread #2
==64886== Locks held: none
==64886==    at 0x11D6AB: release (unique_ptr.h:376)
==64886==    by 0x11D6AB: unique_ptr (unique_ptr.h:250)
==64886==    by 0x11D6AB: operator() (future:1372)
==64886==    by 0x11D6AB: std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<std::function<void ()>, std::allocator<int>, void ()>::_M_run()::{lambda()#1}, void> >::_M_invoke(std::_Any_data const&) (std_function.h:286)
==64886==    by 0x11DCB8: operator() (std_function.h:690)
==64886==    by 0x11DCB8: std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) (future:561)
==64886==    by 0x4BDD87E: __pthread_once_slow (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x13F658: __gthread_once (gthr-default.h:700)
==64886==    by 0x13F658: call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()>*, bool*> (mutex:683)
==64886==    by 0x13F658: _M_set_result (future:401)
==64886==    by 0x13F658: _M_run (future:1423)
==64886==    by 0x13F658: operator() (future:1551)
==64886==    by 0x13F658: operator() (executor.h:79)
==64886==    by 0x13F658: std::_Function_handler<void (), std::future<decltype ({parm#1}({parm#2}...))> da::executor::Executor::add<da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::{lambda()#1}>(da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::{lambda()#1}&&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) (std_function.h:300)
==64886==    by 0x119DAF: operator() (std_function.h:690)
==64886==    by 0x119DAF: da::executor::Executor::Worker::operator()() (executor.cc:56)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==  Address 0x4ddc880 is 48 bytes inside a block of size 88 alloc'd
==64886==    at 0x4839E3F: operator new(unsigned long) (vg_replace_malloc.c:344)
==64886==    by 0x13FDFD: allocate (new_allocator.h:114)
==64886==    by 0x13FDFD: allocate (alloc_traits.h:444)
==64886==    by 0x13FDFD: __allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<std::__future_base::_Task_state<std::function<void()>, std::allocator<int>, void()>, std::allocator<int>, (__gnu_cxx::_Lock_policy)2> > > (allocated_ptr.h:97)
==64886==    by 0x13FDFD: __shared_count<std::__future_base::_Task_state<std::function<void()>, std::allocator<int>, void()>, std::allocator<int>, std::function<void()>&, const std::allocator<int>&> (shared_ptr_base.h:677)
==64886==    by 0x13FDFD: __shared_ptr<std::allocator<int>, std::function<void()>&, const std::allocator<int>&> (shared_ptr_base.h:1344)
==64886==    by 0x13FDFD: shared_ptr<std::allocator<int>, std::function<void()>&, const std::allocator<int>&> (shared_ptr.h:359)
==64886==    by 0x13FDFD: allocate_shared<std::__future_base::_Task_state<std::function<void()>, std::allocator<int>, void()>, std::allocator<int>, std::function<void()>&, const std::allocator<int>&> (shared_ptr.h:702)
==64886==    by 0x13FDFD: __create_task_state<void(), std::function<void()>&, std::allocator<int> > (future:1454)
==64886==    by 0x13FDFD: packaged_task<std::function<void()>&, std::allocator<int> > (future:1501)
==64886==    by 0x13FDFD: packaged_task<std::function<void()>&> (future:1492)
==64886==    by 0x13FDFD: construct<std::packaged_task<void()>, std::function<void()>&> (new_allocator.h:147)
==64886==    by 0x13FDFD: construct<std::packaged_task<void()>, std::function<void()>&> (alloc_traits.h:484)
==64886==    by 0x13FDFD: _Sp_counted_ptr_inplace<std::function<void()>&> (shared_ptr_base.h:548)
==64886==    by 0x13FDFD: __shared_count<std::packaged_task<void()>, std::allocator<std::packaged_task<void()> >, std::function<void()>&> (shared_ptr_base.h:679)
==64886==    by 0x13FDFD: __shared_ptr<std::allocator<std::packaged_task<void()> >, std::function<void()>&> (shared_ptr_base.h:1344)
==64886==    by 0x13FDFD: shared_ptr<std::allocator<std::packaged_task<void()> >, std::function<void()>&> (shared_ptr.h:359)
==64886==    by 0x13FDFD: allocate_shared<std::packaged_task<void()>, std::allocator<std::packaged_task<void()> >, std::function<void()>&> (shared_ptr.h:702)
==64886==    by 0x13FDFD: make_shared<std::packaged_task<void()>, std::function<void()>&> (shared_ptr.h:718)
==64886==    by 0x13FDFD: add<da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::<lambda()> > (executor.h:76)
==64886==    by 0x13FDFD: da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*) (receiver.cc:28)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4CED2D2: clone (in /usr/lib/libc-2.30.so)
==64886==  Block was alloc'd by thread #11
==64886== 
==64886== ----------------------------------------------------------------
==64886== 
==64886== Possible data race during write of size 8 at 0x4DDC880 by thread #11
==64886== Locks held: none
==64886==    at 0x11DDEB: release (unique_ptr.h:376)
==64886==    by 0x11DDEB: unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter> (unique_ptr.h:264)
==64886==    by 0x11DDEB: ~packaged_task (future:1507)
==64886==    by 0x11DDEB: destroy<std::packaged_task<void()> > (new_allocator.h:153)
==64886==    by 0x11DDEB: destroy<std::packaged_task<void()> > (alloc_traits.h:497)
==64886==    by 0x11DDEB: std::_Sp_counted_ptr_inplace<std::packaged_task<void ()>, std::allocator<std::packaged_task<void ()> >, (__gnu_cxx::_Lock_policy)2>::_M_dispose() (shared_ptr_base.h:557)
==64886==    by 0x14007A: _M_release (shared_ptr_base.h:155)
==64886==    by 0x14007A: _M_release (shared_ptr_base.h:148)
==64886==    by 0x14007A: ~__shared_count (shared_ptr_base.h:730)
==64886==    by 0x14007A: ~__shared_ptr (shared_ptr_base.h:1169)
==64886==    by 0x14007A: ~shared_ptr (shared_ptr.h:103)
==64886==    by 0x14007A: add<da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::<lambda()> > (executor.h:76)
==64886==    by 0x14007A: da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*) (receiver.cc:28)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4CED2D2: clone (in /usr/lib/libc-2.30.so)
==64886== 
==64886== This conflicts with a previous write of size 8 by thread #2
==64886== Locks held: none
==64886==    at 0x11D6AB: release (unique_ptr.h:376)
==64886==    by 0x11D6AB: unique_ptr (unique_ptr.h:250)
==64886==    by 0x11D6AB: operator() (future:1372)
==64886==    by 0x11D6AB: std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<std::function<void ()>, std::allocator<int>, void ()>::_M_run()::{lambda()#1}, void> >::_M_invoke(std::_Any_data const&) (std_function.h:286)
==64886==    by 0x11DCB8: operator() (std_function.h:690)
==64886==    by 0x11DCB8: std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) (future:561)
==64886==    by 0x4BDD87E: __pthread_once_slow (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x13F658: __gthread_once (gthr-default.h:700)
==64886==    by 0x13F658: call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()>*, bool*> (mutex:683)
==64886==    by 0x13F658: _M_set_result (future:401)
==64886==    by 0x13F658: _M_run (future:1423)
==64886==    by 0x13F658: operator() (future:1551)
==64886==    by 0x13F658: operator() (executor.h:79)
==64886==    by 0x13F658: std::_Function_handler<void (), std::future<decltype ({parm#1}({parm#2}...))> da::executor::Executor::add<da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::{lambda()#1}>(da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::{lambda()#1}&&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) (std_function.h:300)
==64886==    by 0x119DAF: operator() (std_function.h:690)
==64886==    by 0x119DAF: da::executor::Executor::Worker::operator()() (executor.cc:56)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==  Address 0x4ddc880 is 48 bytes inside a block of size 88 alloc'd
==64886==    at 0x4839E3F: operator new(unsigned long) (vg_replace_malloc.c:344)
==64886==    by 0x13FDFD: allocate (new_allocator.h:114)
==64886==    by 0x13FDFD: allocate (alloc_traits.h:444)
==64886==    by 0x13FDFD: __allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<std::__future_base::_Task_state<std::function<void()>, std::allocator<int>, void()>, std::allocator<int>, (__gnu_cxx::_Lock_policy)2> > > (allocated_ptr.h:97)
==64886==    by 0x13FDFD: __shared_count<std::__future_base::_Task_state<std::function<void()>, std::allocator<int>, void()>, std::allocator<int>, std::function<void()>&, const std::allocator<int>&> (shared_ptr_base.h:677)
==64886==    by 0x13FDFD: __shared_ptr<std::allocator<int>, std::function<void()>&, const std::allocator<int>&> (shared_ptr_base.h:1344)
==64886==    by 0x13FDFD: shared_ptr<std::allocator<int>, std::function<void()>&, const std::allocator<int>&> (shared_ptr.h:359)
==64886==    by 0x13FDFD: allocate_shared<std::__future_base::_Task_state<std::function<void()>, std::allocator<int>, void()>, std::allocator<int>, std::function<void()>&, const std::allocator<int>&> (shared_ptr.h:702)
==64886==    by 0x13FDFD: __create_task_state<void(), std::function<void()>&, std::allocator<int> > (future:1454)
==64886==    by 0x13FDFD: packaged_task<std::function<void()>&, std::allocator<int> > (future:1501)
==64886==    by 0x13FDFD: packaged_task<std::function<void()>&> (future:1492)
==64886==    by 0x13FDFD: construct<std::packaged_task<void()>, std::function<void()>&> (new_allocator.h:147)
==64886==    by 0x13FDFD: construct<std::packaged_task<void()>, std::function<void()>&> (alloc_traits.h:484)
==64886==    by 0x13FDFD: _Sp_counted_ptr_inplace<std::function<void()>&> (shared_ptr_base.h:548)
==64886==    by 0x13FDFD: __shared_count<std::packaged_task<void()>, std::allocator<std::packaged_task<void()> >, std::function<void()>&> (shared_ptr_base.h:679)
==64886==    by 0x13FDFD: __shared_ptr<std::allocator<std::packaged_task<void()> >, std::function<void()>&> (shared_ptr_base.h:1344)
==64886==    by 0x13FDFD: shared_ptr<std::allocator<std::packaged_task<void()> >, std::function<void()>&> (shared_ptr.h:359)
==64886==    by 0x13FDFD: allocate_shared<std::packaged_task<void()>, std::allocator<std::packaged_task<void()> >, std::function<void()>&> (shared_ptr.h:702)
==64886==    by 0x13FDFD: make_shared<std::packaged_task<void()>, std::function<void()>&> (shared_ptr.h:718)
==64886==    by 0x13FDFD: add<da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::<lambda()> > (executor.h:76)
==64886==    by 0x13FDFD: da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*) (receiver.cc:28)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4CED2D2: clone (in /usr/lib/libc-2.30.so)
==64886==  Block was alloc'd by thread #11
==64886== 
==64886== ----------------------------------------------------------------
==64886== 
==64886== Possible data race during write of size 8 at 0x4DDC860 by thread #11
==64886== Locks held: none
==64886==    at 0x11DD1B: ~_Task_state (future:1407)
==64886==    by 0x11DD1B: destroy<std::__future_base::_Task_state<std::function<void()>, std::allocator<int>, void()> > (new_allocator.h:153)
==64886==    by 0x11DD1B: destroy<std::__future_base::_Task_state<std::function<void()>, std::allocator<int>, void()> > (alloc_traits.h:497)
==64886==    by 0x11DD1B: std::_Sp_counted_ptr_inplace<std::__future_base::_Task_state<std::function<void ()>, std::allocator<int>, void ()>, std::allocator<int>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() (shared_ptr_base.h:557)
==64886==    by 0x140031: _M_release (shared_ptr_base.h:155)
==64886==    by 0x140031: _M_release (shared_ptr_base.h:148)
==64886==    by 0x140031: ~__shared_count (shared_ptr_base.h:730)
==64886==    by 0x140031: ~__shared_ptr (shared_ptr_base.h:1169)
==64886==    by 0x140031: ~shared_ptr (shared_ptr.h:103)
==64886==    by 0x140031: ~__basic_future (future:671)
==64886==    by 0x140031: ~future (future:847)
==64886==    by 0x140031: da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*) (receiver.cc:28)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4CED2D2: clone (in /usr/lib/libc-2.30.so)
==64886== 
==64886== This conflicts with a previous read of size 8 by thread #2
==64886== Locks held: none
==64886==    at 0x13F55F: operator() (future:1551)
==64886==    by 0x13F55F: operator() (executor.h:79)
==64886==    by 0x13F55F: std::_Function_handler<void (), std::future<decltype ({parm#1}({parm#2}...))> da::executor::Executor::add<da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::{lambda()#1}>(da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::{lambda()#1}&&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) (std_function.h:300)
==64886==    by 0x119DAF: operator() (std_function.h:690)
==64886==    by 0x119DAF: da::executor::Executor::Worker::operator()() (executor.cc:56)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4CED2D2: clone (in /usr/lib/libc-2.30.so)
==64886==  Address 0x4ddc860 is 16 bytes inside a block of size 88 alloc'd
==64886==    at 0x4839E3F: operator new(unsigned long) (vg_replace_malloc.c:344)
==64886==    by 0x13FDFD: allocate (new_allocator.h:114)
==64886==    by 0x13FDFD: allocate (alloc_traits.h:444)
==64886==    by 0x13FDFD: __allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<std::__future_base::_Task_state<std::function<void()>, std::allocator<int>, void()>, std::allocator<int>, (__gnu_cxx::_Lock_policy)2> > > (allocated_ptr.h:97)
==64886==    by 0x13FDFD: __shared_count<std::__future_base::_Task_state<std::function<void()>, std::allocator<int>, void()>, std::allocator<int>, std::function<void()>&, const std::allocator<int>&> (shared_ptr_base.h:677)
==64886==    by 0x13FDFD: __shared_ptr<std::allocator<int>, std::function<void()>&, const std::allocator<int>&> (shared_ptr_base.h:1344)
==64886==    by 0x13FDFD: shared_ptr<std::allocator<int>, std::function<void()>&, const std::allocator<int>&> (shared_ptr.h:359)
==64886==    by 0x13FDFD: allocate_shared<std::__future_base::_Task_state<std::function<void()>, std::allocator<int>, void()>, std::allocator<int>, std::function<void()>&, const std::allocator<int>&> (shared_ptr.h:702)
==64886==    by 0x13FDFD: __create_task_state<void(), std::function<void()>&, std::allocator<int> > (future:1454)
==64886==    by 0x13FDFD: packaged_task<std::function<void()>&, std::allocator<int> > (future:1501)
==64886==    by 0x13FDFD: packaged_task<std::function<void()>&> (future:1492)
==64886==    by 0x13FDFD: construct<std::packaged_task<void()>, std::function<void()>&> (new_allocator.h:147)
==64886==    by 0x13FDFD: construct<std::packaged_task<void()>, std::function<void()>&> (alloc_traits.h:484)
==64886==    by 0x13FDFD: _Sp_counted_ptr_inplace<std::function<void()>&> (shared_ptr_base.h:548)
==64886==    by 0x13FDFD: __shared_count<std::packaged_task<void()>, std::allocator<std::packaged_task<void()> >, std::function<void()>&> (shared_ptr_base.h:679)
==64886==    by 0x13FDFD: __shared_ptr<std::allocator<std::packaged_task<void()> >, std::function<void()>&> (shared_ptr_base.h:1344)
==64886==    by 0x13FDFD: shared_ptr<std::allocator<std::packaged_task<void()> >, std::function<void()>&> (shared_ptr.h:359)
==64886==    by 0x13FDFD: allocate_shared<std::packaged_task<void()>, std::allocator<std::packaged_task<void()> >, std::function<void()>&> (shared_ptr.h:702)
==64886==    by 0x13FDFD: make_shared<std::packaged_task<void()>, std::function<void()>&> (shared_ptr.h:718)
==64886==    by 0x13FDFD: add<da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::<lambda()> > (executor.h:76)
==64886==    by 0x13FDFD: da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*) (receiver.cc:28)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4CED2D2: clone (in /usr/lib/libc-2.30.so)
==64886==  Block was alloc'd by thread #11
==64886== 
==64886== ----------------------------------------------------------------
==64886== 
==64886== Possible data race during read of size 8 at 0x4DDC868 by thread #11
==64886== Locks held: none
==64886==    at 0x11DD5F: ~unique_ptr (unique_ptr.h:283)
==64886==    by 0x11DD5F: ~_State_baseV2 (future:328)
==64886==    by 0x11DD5F: ~_Task_state_base (future:1380)
==64886==    by 0x11DD5F: ~_Task_state (future:1407)
==64886==    by 0x11DD5F: destroy<std::__future_base::_Task_state<std::function<void()>, std::allocator<int>, void()> > (new_allocator.h:153)
==64886==    by 0x11DD5F: destroy<std::__future_base::_Task_state<std::function<void()>, std::allocator<int>, void()> > (alloc_traits.h:497)
==64886==    by 0x11DD5F: std::_Sp_counted_ptr_inplace<std::__future_base::_Task_state<std::function<void ()>, std::allocator<int>, void ()>, std::allocator<int>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() (shared_ptr_base.h:557)
==64886==    by 0x140031: _M_release (shared_ptr_base.h:155)
==64886==    by 0x140031: _M_release (shared_ptr_base.h:148)
==64886==    by 0x140031: ~__shared_count (shared_ptr_base.h:730)
==64886==    by 0x140031: ~__shared_ptr (shared_ptr_base.h:1169)
==64886==    by 0x140031: ~shared_ptr (shared_ptr.h:103)
==64886==    by 0x140031: ~__basic_future (future:671)
==64886==    by 0x140031: ~future (future:847)
==64886==    by 0x140031: da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*) (receiver.cc:28)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4CED2D2: clone (in /usr/lib/libc-2.30.so)
==64886== 
==64886== This conflicts with a previous write of size 8 by thread #2
==64886== Locks held: none
==64886==    at 0x11DCC9: _M_assign<std::__future_base::_Result_base*, std::__future_base::_Result_base::_Deleter> (tuple:308)
==64886==    by 0x11DCC9: operator= (tuple:1220)
==64886==    by 0x11DCC9: operator= (unique_ptr.h:120)
==64886==    by 0x11DCC9: swap<std::__uniq_ptr_impl<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> > (move.h:194)
==64886==    by 0x11DCC9: swap (unique_ptr.h:402)
==64886==    by 0x11DCC9: std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) (future:566)
==64886==    by 0x4BDD87E: __pthread_once_slow (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x13F658: __gthread_once (gthr-default.h:700)
==64886==    by 0x13F658: call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()>*, bool*> (mutex:683)
==64886==    by 0x13F658: _M_set_result (future:401)
==64886==    by 0x13F658: _M_run (future:1423)
==64886==    by 0x13F658: operator() (future:1551)
==64886==    by 0x13F658: operator() (executor.h:79)
==64886==    by 0x13F658: std::_Function_handler<void (), std::future<decltype ({parm#1}({parm#2}...))> da::executor::Executor::add<da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::{lambda()#1}>(da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::{lambda()#1}&&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) (std_function.h:300)
==64886==    by 0x119DAF: operator() (std_function.h:690)
==64886==    by 0x119DAF: da::executor::Executor::Worker::operator()() (executor.cc:56)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4CED2D2: clone (in /usr/lib/libc-2.30.so)
==64886==  Address 0x4ddc868 is 24 bytes inside a block of size 88 alloc'd
==64886==    at 0x4839E3F: operator new(unsigned long) (vg_replace_malloc.c:344)
==64886==    by 0x13FDFD: allocate (new_allocator.h:114)
==64886==    by 0x13FDFD: allocate (alloc_traits.h:444)
==64886==    by 0x13FDFD: __allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<std::__future_base::_Task_state<std::function<void()>, std::allocator<int>, void()>, std::allocator<int>, (__gnu_cxx::_Lock_policy)2> > > (allocated_ptr.h:97)
==64886==    by 0x13FDFD: __shared_count<std::__future_base::_Task_state<std::function<void()>, std::allocator<int>, void()>, std::allocator<int>, std::function<void()>&, const std::allocator<int>&> (shared_ptr_base.h:677)
==64886==    by 0x13FDFD: __shared_ptr<std::allocator<int>, std::function<void()>&, const std::allocator<int>&> (shared_ptr_base.h:1344)
==64886==    by 0x13FDFD: shared_ptr<std::allocator<int>, std::function<void()>&, const std::allocator<int>&> (shared_ptr.h:359)
==64886==    by 0x13FDFD: allocate_shared<std::__future_base::_Task_state<std::function<void()>, std::allocator<int>, void()>, std::allocator<int>, std::function<void()>&, const std::allocator<int>&> (shared_ptr.h:702)
==64886==    by 0x13FDFD: __create_task_state<void(), std::function<void()>&, std::allocator<int> > (future:1454)
==64886==    by 0x13FDFD: packaged_task<std::function<void()>&, std::allocator<int> > (future:1501)
==64886==    by 0x13FDFD: packaged_task<std::function<void()>&> (future:1492)
==64886==    by 0x13FDFD: construct<std::packaged_task<void()>, std::function<void()>&> (new_allocator.h:147)
==64886==    by 0x13FDFD: construct<std::packaged_task<void()>, std::function<void()>&> (alloc_traits.h:484)
==64886==    by 0x13FDFD: _Sp_counted_ptr_inplace<std::function<void()>&> (shared_ptr_base.h:548)
==64886==    by 0x13FDFD: __shared_count<std::packaged_task<void()>, std::allocator<std::packaged_task<void()> >, std::function<void()>&> (shared_ptr_base.h:679)
==64886==    by 0x13FDFD: __shared_ptr<std::allocator<std::packaged_task<void()> >, std::function<void()>&> (shared_ptr_base.h:1344)
==64886==    by 0x13FDFD: shared_ptr<std::allocator<std::packaged_task<void()> >, std::function<void()>&> (shared_ptr.h:359)
==64886==    by 0x13FDFD: allocate_shared<std::packaged_task<void()>, std::allocator<std::packaged_task<void()> >, std::function<void()>&> (shared_ptr.h:702)
==64886==    by 0x13FDFD: make_shared<std::packaged_task<void()>, std::function<void()>&> (shared_ptr.h:718)
==64886==    by 0x13FDFD: add<da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::<lambda()> > (executor.h:76)
==64886==    by 0x13FDFD: da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*) (receiver.cc:28)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4CED2D2: clone (in /usr/lib/libc-2.30.so)
==64886==  Block was alloc'd by thread #11
==64886== 
==64886== ---Thread-Announcement------------------------------------------
==64886== 
==64886== Thread #1 is the program's root thread
==64886== 
==64886== ----------------------------------------------------------------
==64886== 
==64886== Possible data race during write of size 1 at 0x15BF40 by thread #2
==64886== Locks held: none
==64886==    at 0x140966: store (atomic_base.h:397)
==64886==    by 0x140966: operator= (atomic_base.h:290)
==64886==    by 0x140966: operator= (atomic:81)
==64886==    by 0x140966: (anonymous namespace)::exitHandler(int) (da_proc.cc:48)
==64886==    by 0x4C29FAF: ??? (in /usr/lib/libc-2.30.so)
==64886==    by 0x4BDBC42: pthread_cond_wait@@GLIBC_2.3.2 (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x483FA13: pthread_cond_wait_WRK (hg_intercepts.c:1203)
==64886==    by 0x494C1B0: __gthread_cond_wait (gthr-default.h:865)
==64886==    by 0x494C1B0: std::condition_variable::wait(std::unique_lock<std::mutex>&) (condition_variable.cc:53)
==64886==    by 0x119C3A: wait<da::executor::Executor::Worker::operator()()::<lambda()> > (condition_variable:101)
==64886==    by 0x119C3A: da::executor::Executor::Worker::operator()() (executor.cc:45)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4CED2D2: clone (in /usr/lib/libc-2.30.so)
==64886== 
==64886== This conflicts with a previous read of size 1 by thread #1
==64886== Locks held: none
==64886==    at 0x115299: load (atomic_base.h:419)
==64886==    by 0x115299: operator bool (atomic:88)
==64886==    by 0x115299: main (da_proc.cc:168)
==64886==  Address 0x15bf40 is 0 bytes inside data symbol "_ZN12_GLOBAL__N_18can_stopE"
==64886== 
==64886== ----------------------------------------------------------------
==64886== 
==64886== Possible data race during read of size 1 at 0x15BF40 by thread #1
==64886== Locks held: none
==64886==    at 0x115299: load (atomic_base.h:419)
==64886==    by 0x115299: operator bool (atomic:88)
==64886==    by 0x115299: main (da_proc.cc:168)
==64886== 
==64886== This conflicts with a previous write of size 1 by thread #2
==64886== Locks held: none
==64886==    at 0x140966: store (atomic_base.h:397)
==64886==    by 0x140966: operator= (atomic_base.h:290)
==64886==    by 0x140966: operator= (atomic:81)
==64886==    by 0x140966: (anonymous namespace)::exitHandler(int) (da_proc.cc:48)
==64886==    by 0x4C29FAF: ??? (in /usr/lib/libc-2.30.so)
==64886==    by 0x4BDBC42: pthread_cond_wait@@GLIBC_2.3.2 (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x483FA13: pthread_cond_wait_WRK (hg_intercepts.c:1203)
==64886==    by 0x494C1B0: __gthread_cond_wait (gthr-default.h:865)
==64886==    by 0x494C1B0: std::condition_variable::wait(std::unique_lock<std::mutex>&) (condition_variable.cc:53)
==64886==    by 0x119C3A: wait<da::executor::Executor::Worker::operator()()::<lambda()> > (condition_variable:101)
==64886==    by 0x119C3A: da::executor::Executor::Worker::operator()() (executor.cc:45)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==  Address 0x15bf40 is 0 bytes inside data symbol "_ZN12_GLOBAL__N_18can_stopE"
==64886== 
==64886== ----------------------------------------------------------------
==64886== 
==64886== Possible data race during write of size 1 at 0x4DCF960 by thread #1
==64886== Locks held: none
==64886==    at 0x115326: store (atomic_base.h:397)
==64886==    by 0x115326: operator= (atomic_base.h:290)
==64886==    by 0x115326: operator= (atomic:81)
==64886==    by 0x115326: stop (receiver.h:21)
==64886==    by 0x115326: exitThreads (da_proc.cc:58)
==64886==    by 0x115326: main (da_proc.cc:181)
==64886== 
==64886== This conflicts with a previous read of size 1 by thread #11
==64886== Locks held: none
==64886==    at 0x13FBD2: load (atomic_base.h:419)
==64886==    by 0x13FBD2: operator bool (atomic:88)
==64886==    by 0x13FBD2: isAlive (receiver.h:23)
==64886==    by 0x13FBD2: da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*) (receiver.cc:11)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4CED2D2: clone (in /usr/lib/libc-2.30.so)
==64886==  Address 0x4dcf960 is 0 bytes inside a block of size 24 alloc'd
==64886==    at 0x4839E3F: operator new(unsigned long) (vg_replace_malloc.c:344)
==64886==    by 0x1151A6: make_unique<da::receiver::Receiver, da::executor::Executor*, da::socket::UDPSocket*> (unique_ptr.h:849)
==64886==    by 0x1151A6: main (da_proc.cc:155)
==64886==  Block was alloc'd by thread #1
==64886== 
==64886== ---Thread-Announcement------------------------------------------
==64886== 
==64886== Thread #3 was created
==64886==    at 0x4CED2C2: clone (in /usr/lib/libc-2.30.so)
==64886==    by 0x4BD438B: create_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4BD5CFB: pthread_create@@GLIBC_2.2.5 (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x483F677: pthread_create_WRK (hg_intercepts.c:427)
==64886==    by 0x49521A9: __gthread_create (gthr-default.h:663)
==64886==    by 0x49521A9: std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (thread.cc:135)
==64886==    by 0x11A05F: thread<da::executor::Executor::Worker> (thread:130)
==64886==    by 0x11A05F: da::executor::Executor::Executor(int) (executor.cc:12)
==64886==    by 0x114CC2: make_unique<da::executor::Executor, long unsigned int> (unique_ptr.h:849)
==64886==    by 0x114CC2: main (da_proc.cc:131)
==64886== 
==64886== ----------------------------------------------------------------
==64886== 
==64886==  Lock at 0x4DCD1C0 was first observed
==64886==    at 0x483CC3F: mutex_lock_WRK (hg_intercepts.c:909)
==64886==    by 0x119ADD: __gthread_mutex_lock (gthr-default.h:749)
==64886==    by 0x119ADD: lock (std_mutex.h:100)
==64886==    by 0x119ADD: lock (unique_lock.h:141)
==64886==    by 0x119ADD: unique_lock (unique_lock.h:71)
==64886==    by 0x119ADD: da::executor::Executor::Worker::operator()() (executor.cc:43)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4CED2D2: clone (in /usr/lib/libc-2.30.so)
==64886==  Address 0x4dcd1c0 is 160 bytes inside a block of size 248 alloc'd
==64886==    at 0x4839E3F: operator new(unsigned long) (vg_replace_malloc.c:344)
==64886==    by 0x114CB4: make_unique<da::executor::Executor, long unsigned int> (unique_ptr.h:849)
==64886==    by 0x114CB4: main (da_proc.cc:131)
==64886==  Block was alloc'd by thread #1
==64886== 
==64886== Possible data race during write of size 1 at 0x4DCD120 by thread #1
==64886== Locks held: none
==64886==    at 0x11A13B: store (atomic_base.h:397)
==64886==    by 0x11A13B: operator= (atomic_base.h:290)
==64886==    by 0x11A13B: operator= (atomic:81)
==64886==    by 0x11A13B: da::executor::Executor::waitForCompletion() (executor.cc:23)
==64886==    by 0x11533C: stop (executor.h:39)
==64886==    by 0x11533C: exitThreads (da_proc.cc:63)
==64886==    by 0x11533C: main (da_proc.cc:181)
==64886== 
==64886== This conflicts with a previous read of size 1 by thread #3
==64886== Locks held: 1, at address 0x4DCD1C0
==64886==    at 0x119BE0: load (atomic_base.h:419)
==64886==    by 0x119BE0: operator bool (atomic:88)
==64886==    by 0x119BE0: isAlive (executor.h:34)
==64886==    by 0x119BE0: operator() (executor.cc:46)
==64886==    by 0x119BE0: wait<da::executor::Executor::Worker::operator()()::<lambda()> > (condition_variable:100)
==64886==    by 0x119BE0: da::executor::Executor::Worker::operator()() (executor.cc:45)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4CED2D2: clone (in /usr/lib/libc-2.30.so)
==64886==  Address 0x4dcd120 is 0 bytes inside a block of size 248 alloc'd
==64886==    at 0x4839E3F: operator new(unsigned long) (vg_replace_malloc.c:344)
==64886==    by 0x114CB4: make_unique<da::executor::Executor, long unsigned int> (unique_ptr.h:849)
==64886==    by 0x114CB4: main (da_proc.cc:131)
==64886==  Block was alloc'd by thread #1
==64886== 
==64886== ----------------------------------------------------------------
==64886== 
==64886==  Lock at 0x4DCD1C0 was first observed
==64886==    at 0x483CC3F: mutex_lock_WRK (hg_intercepts.c:909)
==64886==    by 0x119ADD: __gthread_mutex_lock (gthr-default.h:749)
==64886==    by 0x119ADD: lock (std_mutex.h:100)
==64886==    by 0x119ADD: lock (unique_lock.h:141)
==64886==    by 0x119ADD: unique_lock (unique_lock.h:71)
==64886==    by 0x119ADD: da::executor::Executor::Worker::operator()() (executor.cc:43)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4CED2D2: clone (in /usr/lib/libc-2.30.so)
==64886==  Address 0x4dcd1c0 is 160 bytes inside a block of size 248 alloc'd
==64886==    at 0x4839E3F: operator new(unsigned long) (vg_replace_malloc.c:344)
==64886==    by 0x114CB4: make_unique<da::executor::Executor, long unsigned int> (unique_ptr.h:849)
==64886==    by 0x114CB4: main (da_proc.cc:131)
==64886==  Block was alloc'd by thread #1
==64886== 
==64886== Possible data race during write of size 1 at 0x4DCD168 by thread #1
==64886== Locks held: none
==64886==    at 0x11A146: store (atomic_base.h:397)
==64886==    by 0x11A146: operator= (atomic_base.h:290)
==64886==    by 0x11A146: operator= (atomic:81)
==64886==    by 0x11A146: stop (thread_safe_queue.h:27)
==64886==    by 0x11A146: da::executor::Executor::waitForCompletion() (executor.cc:24)
==64886==    by 0x11533C: stop (executor.h:39)
==64886==    by 0x11533C: exitThreads (da_proc.cc:63)
==64886==    by 0x11533C: main (da_proc.cc:181)
==64886== 
==64886== This conflicts with a previous read of size 1 by thread #3
==64886== Locks held: 1, at address 0x4DCD1C0
==64886==    at 0x119BEF: load (atomic_base.h:419)
==64886==    by 0x119BEF: operator bool (atomic:88)
==64886==    by 0x119BEF: empty (thread_safe_queue.h:19)
==64886==    by 0x119BEF: operator() (executor.cc:46)
==64886==    by 0x119BEF: wait<da::executor::Executor::Worker::operator()()::<lambda()> > (condition_variable:100)
==64886==    by 0x119BEF: da::executor::Executor::Worker::operator()() (executor.cc:45)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4CED2D2: clone (in /usr/lib/libc-2.30.so)
==64886==  Address 0x4dcd168 is 72 bytes inside a block of size 248 alloc'd
==64886==    at 0x4839E3F: operator new(unsigned long) (vg_replace_malloc.c:344)
==64886==    by 0x114CB4: make_unique<da::executor::Executor, long unsigned int> (unique_ptr.h:849)
==64886==    by 0x114CB4: main (da_proc.cc:131)
==64886==  Block was alloc'd by thread #1
==64886== 
==64886== ----------------------------------------------------------------
==64886== 
==64886== Possible data race during read of size 1 at 0x4DCF960 by thread #11
==64886== Locks held: none
==64886==    at 0x13FC8B: load (atomic_base.h:419)
==64886==    by 0x13FC8B: operator bool (atomic:88)
==64886==    by 0x13FC8B: isAlive (receiver.h:23)
==64886==    by 0x13FC8B: da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*) (receiver.cc:25)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4CED2D2: clone (in /usr/lib/libc-2.30.so)
==64886== 
==64886== This conflicts with a previous write of size 1 by thread #1
==64886== Locks held: none
==64886==    at 0x115326: store (atomic_base.h:397)
==64886==    by 0x115326: operator= (atomic_base.h:290)
==64886==    by 0x115326: operator= (atomic:81)
==64886==    by 0x115326: stop (receiver.h:21)
==64886==    by 0x115326: exitThreads (da_proc.cc:58)
==64886==    by 0x115326: main (da_proc.cc:181)
==64886==  Address 0x4dcf960 is 0 bytes inside a block of size 24 alloc'd
==64886==    at 0x4839E3F: operator new(unsigned long) (vg_replace_malloc.c:344)
==64886==    by 0x1151A6: make_unique<da::receiver::Receiver, da::executor::Executor*, da::socket::UDPSocket*> (unique_ptr.h:849)
==64886==    by 0x1151A6: main (da_proc.cc:155)
==64886==  Block was alloc'd by thread #1
==64886== 
==64886== ---Thread-Announcement------------------------------------------
==64886== 
==64886== Thread #6 was created
==64886==    at 0x4CED2C2: clone (in /usr/lib/libc-2.30.so)
==64886==    by 0x4BD438B: create_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4BD5CFB: pthread_create@@GLIBC_2.2.5 (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x483F677: pthread_create_WRK (hg_intercepts.c:427)
==64886==    by 0x49521A9: __gthread_create (gthr-default.h:663)
==64886==    by 0x49521A9: std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (thread.cc:135)
==64886==    by 0x11A05F: thread<da::executor::Executor::Worker> (thread:130)
==64886==    by 0x11A05F: da::executor::Executor::Executor(int) (executor.cc:12)
==64886==    by 0x114CC2: make_unique<da::executor::Executor, long unsigned int> (unique_ptr.h:849)
==64886==    by 0x114CC2: main (da_proc.cc:131)
==64886== 
==64886== ----------------------------------------------------------------
==64886== 
==64886== Possible data race during read of size 8 at 0xA1C2D38 by thread #6
==64886== Locks held: none
==64886==    at 0x13F2FA: operator() (receiver.cc:29)
==64886==    by 0x13F2FA: __invoke_impl<void, da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::<lambda()>&> (invoke.h:60)
==64886==    by 0x13F2FA: __invoke<da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::<lambda()>&> (invoke.h:95)
==64886==    by 0x13F2FA: __call<void> (functional:400)
==64886==    by 0x13F2FA: operator()<> (functional:484)
==64886==    by 0x13F2FA: std::_Function_handler<void (), std::_Bind<da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::{lambda()#1} ()> >::_M_invoke(std::_Any_data const&) (std_function.h:300)
==64886==    by 0x11D6A4: operator() (std_function.h:690)
==64886==    by 0x11D6A4: __invoke_impl<void, std::function<void()>&> (invoke.h:60)
==64886==    by 0x11D6A4: __invoke<std::function<void()>&> (invoke.h:95)
==64886==    by 0x11D6A4: operator() (future:1421)
==64886==    by 0x11D6A4: operator() (future:1362)
==64886==    by 0x11D6A4: std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<std::function<void ()>, std::allocator<int>, void ()>::_M_run()::{lambda()#1}, void> >::_M_invoke(std::_Any_data const&) (std_function.h:286)
==64886==    by 0x11DCB8: operator() (std_function.h:690)
==64886==    by 0x11DCB8: std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) (future:561)
==64886==    by 0x4BDD87E: __pthread_once_slow (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x13F658: __gthread_once (gthr-default.h:700)
==64886==    by 0x13F658: call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()>*, bool*> (mutex:683)
==64886==    by 0x13F658: _M_set_result (future:401)
==64886==    by 0x13F658: _M_run (future:1423)
==64886==    by 0x13F658: operator() (future:1551)
==64886==    by 0x13F658: operator() (executor.h:79)
==64886==    by 0x13F658: std::_Function_handler<void (), std::future<decltype ({parm#1}({parm#2}...))> da::executor::Executor::add<da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::{lambda()#1}>(da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::{lambda()#1}&&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) (std_function.h:300)
==64886==    by 0x119DAF: operator() (std_function.h:690)
==64886==    by 0x119DAF: da::executor::Executor::Worker::operator()() (executor.cc:56)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4CED2D2: clone (in /usr/lib/libc-2.30.so)
==64886==  Address 0xa1c2d38 is on thread #11's stack
==64886==  448 bytes below stack pointer
==64886== 
==64886== 
==64886== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==64886==  Access not within mapped region at address 0x8
==64886==    at 0x1217B4: deliverToURB (fifo.cc:65)
==64886==    by 0x1217B4: da::broadcast::UniformFIFOReliable::deliver(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (fifo.cc:88)
==64886==    by 0x11D6A4: operator() (std_function.h:690)
==64886==    by 0x11D6A4: __invoke_impl<void, std::function<void()>&> (invoke.h:60)
==64886==    by 0x11D6A4: __invoke<std::function<void()>&> (invoke.h:95)
==64886==    by 0x11D6A4: operator() (future:1421)
==64886==    by 0x11D6A4: operator() (future:1362)
==64886==    by 0x11D6A4: std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<std::function<void ()>, std::allocator<int>, void ()>::_M_run()::{lambda()#1}, void> >::_M_invoke(std::_Any_data const&) (std_function.h:286)
==64886==    by 0x11DCB8: operator() (std_function.h:690)
==64886==    by 0x11DCB8: std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) (future:561)
==64886==    by 0x4BDD87E: __pthread_once_slow (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x13F658: __gthread_once (gthr-default.h:700)
==64886==    by 0x13F658: call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()>*, bool*> (mutex:683)
==64886==    by 0x13F658: _M_set_result (future:401)
==64886==    by 0x13F658: _M_run (future:1423)
==64886==    by 0x13F658: operator() (future:1551)
==64886==    by 0x13F658: operator() (executor.h:79)
==64886==    by 0x13F658: std::_Function_handler<void (), std::future<decltype ({parm#1}({parm#2}...))> da::executor::Executor::add<da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::{lambda()#1}>(da::receiver::Receiver::operator()(da::broadcast::UniformFIFOReliable*)::{lambda()#1}&&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) (std_function.h:300)
==64886==    by 0x119DAF: operator() (std_function.h:690)
==64886==    by 0x119DAF: da::executor::Executor::Worker::operator()() (executor.cc:56)
==64886==    by 0x4951ED3: execute_native_thread_routine (thread.cc:80)
==64886==    by 0x483F876: mythread_wrapper (hg_intercepts.c:389)
==64886==    by 0x4BD54CE: start_thread (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x4CED2D2: clone (in /usr/lib/libc-2.30.so)
==64886==  If you believe this happened as a result of a stack
==64886==  overflow in your program's main thread (unlikely but
==64886==  possible), you can try to increase the size of the
==64886==  main thread stack using the --main-stacksize= flag.
==64886==  The main thread stack size used in this run was 8388608.
==64886== ----------------------------------------------------------------
==64886== 
==64886== Thread #1: Exiting thread still holds 1 lock
==64886==    at 0x4BDC8F5: pthread_cond_broadcast@@GLIBC_2.3.2 (in /usr/lib/libpthread-2.30.so)
==64886==    by 0x483D578: pthread_cond_broadcast_WRK (hg_intercepts.c:1448)
==64886==    by 0x494C1ED: __gthread_cond_broadcast (gthr-default.h:853)
==64886==    by 0x494C1ED: std::condition_variable::notify_all() (condition_variable.cc:73)
==64886==    by 0x11A3D4: da::executor::Executor::waitForCompletion() (executor.cc:27)
==64886==    by 0x11533C: stop (executor.h:39)
==64886==    by 0x11533C: exitThreads (da_proc.cc:63)
==64886==    by 0x11533C: main (da_proc.cc:181)
==64886== 
==64886== 
==64886== Use --history-level=approx or =none to gain increased speed, at
==64886== the cost of reduced accuracy of conflicting-access information
==64886== For lists of detected and suppressed errors, rerun with: -s
==64886== ERROR SUMMARY: 20 errors from 12 contexts (suppressed: 22515 from 146)
